---
abstract: 'Desk.com perl API'
author:
  - 'binary.com <rakesh@binary.com>'
build_requires:
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.141520'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-Desk
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  MIME::Base64: '0'
  Mojo::Headers: '0'
  Mojo::JSON: '0'
  Mojo::Path: '0'
  Mojo::URL: '0'
  Mojo::UserAgent: '0'
  Moose: '0'
  Net::OAuth::Simple: '0'
  perl: '5.006'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=WWW-Desk
  homepage: https://github.com/binary-com/perl-WWW-Desk
version: '0.02'
